# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Randomについて"
  url = "/about/"
  weight = 20

[[main]]
  name = "ブログ"
  url = "/post/"
  weight = 30

[[main]]
  name = "Project"
  url = "/project/"
  weight = 40

[[main]]
  name = "作品紹介"
  url = "/tags/作品紹介/"
  weight = 40

[[main]]
  name = "部員紹介"
  url = "/authors/"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
